### ISSUE TITLE
Collection of Notion Apps and Libraries

### ISSUE THREAD

**Issue by MaaxGr** [dstotijn/go-notion#1]
Hey David,

i have started to create a open source project that lists open source projects around the new notion api.
https://github.com/MaaxGr/open-source-notionapi-apps

I have added your Go Client to it. Is that okay for you?

BTW: I'm also interested in working with GO, so maybe this Client is a good starting point for me. Haha. :)

Have a nice day
Max

**Comment by dstotijn** [comment]
Awesome! Thanks! 🙏

**Comment by MaaxGr** [comment]
No problem! Feel free to reach me of you have any questions or suggestions :)
