### ISSUE TITLE
"Failed to parse HTTP response" on database query

### ISSUE THREAD

**Issue by maksim77** [dstotijn/go-notion#11]
I'm trying to make a simple query for a selection from the database.
```golang
client := notion.NewClient("secret_0aXXXXXXXXXXX")

res, err := client.QueryDatabase(context.TODO(), "aaaaa-bbbbb-4fc8-b220-xxxxx", &notion.DatabaseQuery{
	Filter: notion.DatabaseQueryFilter{
		Property: "Паркран",
		Text: &notion.TextDatabaseQueryFilter{
			Contains: "parkrun",
		},
	},
})
```

Unfortunately I get an error:

> notion: failed to parse HTTP response: json: cannot unmarshal number into Go struct field DatabaseQueryResponse.results of type notion.NumberMetadata

After tweaking your code a little, I printed out the document that the library receives from the server. There is nothing private in this database, so I bring the document in full:

<details><summary>response.json</summary>
<pre>
{
  "object": "list",
  "results": [
    {
      "object": "page",
      "id": "d2edfb6c-2aa2-4f7a-91f2-xxxxxxx",
      "created_time": "2021-05-24T10:45:05.833Z",
      "last_edited_time": "2021-05-24T10:45:05.833Z",
      "parent": { "type": "database_id", "database_id": "738ab074-8597-4fc8-b220-xxxxxxxxx" },
      "archived": false,
      "properties": {
        "Место среди М/Ж": { "id": "InK~", "type": "number", "number": 25 },
        "Время": {
          "id": "U^E~",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "30:20", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "30:20",
              "href": null
            }
          ]
        },
        "Дата": { "id": "b@g=", "type": "date", "date": { "start": "2021-04-24", "end": null } },
        "Рейтинг": {
          "id": "sJqx",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "44.01%", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "44.01%",
              "href": null
            }
          ]
        },
        "Место в общем зачёте": { "id": "~dWC", "type": "number", "number": 32 },
        "Паркран": {
          "id": "title",
          "type": "title",
          "title": [
            {
              "type": "text",
              "text": { "content": "parkrun Natashinsky", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "parkrun Natashinsky",
              "href": null
            }
          ]
        }
      }
    },
    {
      "object": "page",
      "id": "a8d67af1-0707-4890-9c94-8efa1097b546",
      "created_time": "2021-05-24T10:45:04.432Z",
      "last_edited_time": "2021-05-24T10:45:04.432Z",
      "parent": { "type": "database_id", "database_id": "738ab074-8597-4fc8-b220-813c3dc75528" },
      "archived": false,
      "properties": {
        "Место среди М/Ж": { "id": "InK~", "type": "number", "number": 54 },
        "Время": {
          "id": "U^E~",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "30:49", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "30:49",
              "href": null
            }
          ]
        },
        "Дата": { "id": "b@g=", "type": "date", "date": { "start": "2021-05-22", "end": null } },
        "Рейтинг": {
          "id": "sJqx",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "43.32%", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "43.32%",
              "href": null
            }
          ]
        },
        "Место в общем зачёте": { "id": "~dWC", "type": "number", "number": 74 },
        "Паркран": {
          "id": "title",
          "type": "title",
          "title": [
            {
              "type": "text",
              "text": { "content": "parkrun Natashinsky", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "parkrun Natashinsky",
              "href": null
            }
          ]
        }
      }
    },
    {
      "object": "page",
      "id": "a79f7eba-97df-49f9-8fe5-fd5b60e1a986",
      "created_time": "2021-05-24T10:45:04.420Z",
      "last_edited_time": "2021-05-24T10:45:04.420Z",
      "parent": { "type": "database_id", "database_id": "738ab074-8597-4fc8-b220-813c3dc75528" },
      "archived": false,
      "properties": {
        "Место среди М/Ж": { "id": "InK~", "type": "number", "number": 42 },
        "Время": {
          "id": "U^E~",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "30:27", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "30:27",
              "href": null
            }
          ]
        },
        "Дата": { "id": "b@g=", "type": "date", "date": { "start": "2021-05-08", "end": null } },
        "Рейтинг": {
          "id": "sJqx",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "43.84%", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "43.84%",
              "href": null
            }
          ]
        },
        "Место в общем зачёте": { "id": "~dWC", "type": "number", "number": 60 },
        "Паркран": {
          "id": "title",
          "type": "title",
          "title": [
            {
              "type": "text",
              "text": { "content": "parkrun Natashinsky", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "parkrun Natashinsky",
              "href": null
            }
          ]
        }
      }
    },
    {
      "object": "page",
      "id": "e32c597e-5959-4d14-8d73-a45762bc0fa0",
      "created_time": "2021-05-24T10:45:04.403Z",
      "last_edited_time": "2021-05-24T10:45:04.403Z",
      "parent": { "type": "database_id", "database_id": "738ab074-8597-4fc8-b220-813c3dc75528" },
      "archived": false,
      "properties": {
        "Место среди М/Ж": { "id": "InK~", "type": "number", "number": 46 },
        "Время": {
          "id": "U^E~",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "30:03", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "30:03",
              "href": null
            }
          ]
        },
        "Дата": { "id": "b@g=", "type": "date", "date": { "start": "2021-05-01", "end": null } },
        "Рейтинг": {
          "id": "sJqx",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "44.43%", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "44.43%",
              "href": null
            }
          ]
        },
        "Место в общем зачёте": { "id": "~dWC", "type": "number", "number": 58 },
        "Паркран": {
          "id": "title",
          "type": "title",
          "title": [
            {
              "type": "text",
              "text": { "content": "parkrun Natashinsky", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "parkrun Natashinsky",
              "href": null
            }
          ]
        }
      }
    },
    {
      "object": "page",
      "id": "ac686d42-05bf-4c4d-b1fc-ae7ce0992d79",
      "created_time": "2021-05-24T10:45:04.388Z",
      "last_edited_time": "2021-05-24T10:45:04.388Z",
      "parent": { "type": "database_id", "database_id": "738ab074-8597-4fc8-b220-813c3dc75528" },
      "archived": false,
      "properties": {
        "Место среди М/Ж": { "id": "InK~", "type": "number", "number": 54 },
        "Время": {
          "id": "U^E~",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "31:43", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "31:43",
              "href": null
            }
          ]
        },
        "Дата": { "id": "b@g=", "type": "date", "date": { "start": "2021-04-17", "end": null } },
        "Рейтинг": {
          "id": "sJqx",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "41.83%", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "41.83%",
              "href": null
            }
          ]
        },
        "Место в общем зачёте": { "id": "~dWC", "type": "number", "number": 73 },
        "Паркран": {
          "id": "title",
          "type": "title",
          "title": [
            {
              "type": "text",
              "text": { "content": "parkrun Natashinsky", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "parkrun Natashinsky",
              "href": null
            }
          ]
        }
      }
    },
    {
      "object": "page",
      "id": "df95b4d1-2a51-4ace-8fcb-a886aa2afb74",
      "created_time": "2021-05-24T10:45:04.373Z",
      "last_edited_time": "2021-05-24T10:45:04.373Z",
      "parent": { "type": "database_id", "database_id": "738ab074-8597-4fc8-b220-813c3dc75528" },
      "archived": false,
      "properties": {
        "Место среди М/Ж": { "id": "InK~", "type": "number", "number": 70 },
        "Время": {
          "id": "U^E~",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "32:15", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "32:15",
              "href": null
            }
          ]
        },
        "Дата": { "id": "b@g=", "type": "date", "date": { "start": "2021-04-03", "end": null } },
        "Рейтинг": {
          "id": "sJqx",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "41.14%", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "41.14%",
              "href": null
            }
          ]
        },
        "Место в общем зачёте": { "id": "~dWC", "type": "number", "number": 99 },
        "Паркран": {
          "id": "title",
          "type": "title",
          "title": [
            {
              "type": "text",
              "text": { "content": "parkrun Natashinsky", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "parkrun Natashinsky",
              "href": null
            }
          ]
        }
      }
    },
    {
      "object": "page",
      "id": "b3cb19fc-1e72-4ac5-a74f-197cbc150fa7",
      "created_time": "2021-05-24T10:45:04.362Z",
      "last_edited_time": "2021-05-24T10:45:04.362Z",
      "parent": { "type": "database_id", "database_id": "738ab074-8597-4fc8-b220-813c3dc75528" },
      "archived": false,
      "properties": {
        "Место среди М/Ж": { "id": "InK~", "type": "number", "number": 59 },
        "Время": {
          "id": "U^E~",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "30:29", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "30:29",
              "href": null
            }
          ]
        },
        "Дата": { "id": "b@g=", "type": "date", "date": { "start": "2021-04-10", "end": null } },
        "Рейтинг": {
          "id": "sJqx",
          "type": "rich_text",
          "rich_text": [
            {
              "type": "text",
              "text": { "content": "43.52%", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "43.52%",
              "href": null
            }
          ]
        },
        "Место в общем зачёте": { "id": "~dWC", "type": "number", "number": 81 },
        "Паркран": {
          "id": "title",
          "type": "title",
          "title": [
            {
              "type": "text",
              "text": { "content": "parkrun Natashinsky", "link": null },
              "annotations": {
                "bold": false,
                "italic": false,
                "strikethrough": false,
                "underline": false,
                "code": false,
                "color": "default"
              },
              "plain_text": "parkrun Natashinsky",
              "href": null
            }
          ]
        }
      }
    }
  ],
  "next_cursor": null,
  "has_more": false
}

</pre>
</details>

**Comment by dstotijn** [comment]
Thanks for reporting! Should be fixed now in `v0.3.0`. Number values are always decoded into a `float64`, even if the response data from the Notion API is an integer. I might introduce a custom type later down the road to make it a bit easier to assert and work with number types. But for now, you'll have to manually cast or parse after you've gotten the API response.

**Comment by maksim77** [comment]
Thx!

Unfortunately, instead of the old one, a new error came :)

> notion: failed to parse HTTP response: json: cannot unmarshal string into Go struct field DatabaseQueryResponse.results of type notion.URL

I added new field in database with url type 😂

**Comment by maksim77** [comment]
Should I create a new issue?

**Comment by dstotijn** [comment]
> Should I create a new issue?

Yes please!
