### ISSUE TITLE
"Failed to parse HTTP response" when querying the database if the database contains a field with the url type

### ISSUE THREAD

**Issue by maksim77** [dstotijn/go-notion#12]
If database contains a field with the url type an error occurs:
> notion: failed to parse HTTP response: json: cannot unmarshal string into Go struct field DatabaseQueryResponse.results of type notion.URL

_Originally posted by @maksim77 in https://github.com/dstotijn/go-notion/issues/11#issuecomment-847107164_

**Comment by dstotijn** [comment]
I misinterpreted the docs; doing a fix now, should be there in 30 min or so.

**Comment by dstotijn** [comment]
Should be fixed in `v0.3.1`.
