### ISSUE TITLE
Retrieve File

### ISSUE THREAD

**Issue by RGarbers** [dstotijn/go-notion#22]
Notion added the file url and an expiry time to the files object:
https://developers.notion.com/reference/file-object

Are you planning to add this in the future?

For the beginning, in my opinion, it would be enough to add the two fields to the File struct and maybe add later the functionality of actually downloading the file.

**Comment by dstotijn** [comment]
Yep, I'll be catching up on all missing features, and plan to add them over the next few days/week. 👍

**Comment by dstotijn** [comment]
Added the `url` and `expiry_time` fields in v0.5.
