### ISSUE TITLE
Update database entry Title

### ISSUE THREAD

**Issue by fmartingr** [dstotijn/go-notion#23]
Hello, I'm trying to update a database entry title field (`Name` in my case) but I don't manage to do so. If I use `Name` on the properties it told me to use the `Title`, and using the `Title` does nothing (no errors). I can update other properties without issue.

sample code:

``` go
name := "New name"

page, err := client.UpdatePage(ctx, "<pageid>", notion.UpdatePageParams{
	Title: []notion.RichText{
		{
			PlainText: name,
			Text: &notion.Text{
				Content: product.Name,
			},
		},
	},
)
```

I've tried several combinations, but nothing seems to being able to update the page title. I tried using "Title" as the field name (in case it was some JSON hardcoding) but that didn't work either.

Thanks for your work on this!

**Comment by fmartingr** [comment]
Managed to update it renaming the property to `Title` and using the following code:

``` go
page, err := client.UpdatePage(ctx, "id", notion.UpdatePageParams{
	DatabasePageProperties: &notion.DatabasePageProperties{
		"Title": notion.DatabasePageProperty{
			Type: notion.DBPropTypeTitle,
			Title: []notion.RichText{
				{
					PlainText: name,
					Text: &notion.Text{
						Content: product.Name,
					},
				},
			},
		},
	},
})
```

It didn't work having the property set as `Name` using the following:

``` go
"Name": notion.DatabasePageProperty{
	Type: notion.DBPropTypeTitle,
	Title: []notion.RichText{
		{
			PlainText: name,
			Name: "Name",
			Text: &notion.Text{
				Content: product.Name,
			},
		},
	},
}
```

**Comment by dstotijn** [comment]
The first snippet from your first post should work (although you don't need to provide the `PlainText` field; it's read-only and not used by the API when updating rich text objects). But perhaps `product.Name` is not the same string value as `name`? Thus, I'd advise to test with this snippet:

```go
name := "New name"

page, err := client.UpdatePage(ctx, "<pageid>", notion.UpdatePageParams{
	Title: []notion.RichText{
		{
			PlainText: name,
			Text: &notion.Text{
				Content: name,
			},
		},
	},
})
```

**Comment by fmartingr** [comment]
Yeah sorry @dstotijn , I modified the code (adding `name`) to provide an example but failed to replace `product.Name`; in that case `product.Name` is a `string` and contains something, and it still didn't work. (Just tried it out again).

**Comment by dstotijn** [comment]
Strange; I can't reproduce the issue myself. When I test (with below test program) I'm able to update a page title, both pages with a `workspace` parent type and with a `database` parent type.

Could you maybe try testing with below program?

```go
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/davecgh/go-spew/spew"
	"github.com/dstotijn/go-notion"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	ctx := context.Background()

	var pageID string
	flag.StringVar(&pageID, "page-id", "", "Notion page ID. (Required)")
	flag.Parse()

	if pageID == "" {
		flag.Usage()
		return errors.New("flag `-page-id` must be set")
	}

	apiKey := os.Getenv("NOTION_API_KEY")
	if apiKey == "" {
		return errors.New(`Environment variable "NOTION_API_KEY" must be set.`)
	}

	client := notion.NewClient(apiKey)

	params := notion.UpdatePageParams{
		Title: []notion.RichText{
			{
				Text: &notion.Text{
					Content: "Updated title",
				},
			},
		},
	}

	updatedPage, err := client.UpdatePage(ctx, pageID, params)
	if err != nil {
		return fmt.Errorf("failed to update page: %w", err)
	}

	spew.Dump(updatedPage)

	return nil
}
```

**Comment by fmartingr** [comment]
That code works well for be (using any name on the `Title` database page property), after a few tests, it seems that providing `DatabasePageProperties` along with the Update is causing to ignore the `Title` attribute (I trimmed that from my first posts because I tought it was ireelevant). Am I unable to use the `Title` if I provide my own `DatabasePageProperties`?

I'm not sure if this is intended or not, but is a bit unintuitive for me.

**Comment by dstotijn** [comment]
> (...) it seems that providing `DatabasePageProperties` along with the Update is causing to ignore the `Title` attribute

Ah, nice find!

> I'm not sure if this is intended or not, but is a bit unintuitive for me.

That's not intended. I'll fix this sometime later this week.

**Comment by fmartingr** [comment]
Thank you for the fix @dstotijn ! Now I only need Notion to allow file uploads via API 😬
