### ISSUE TITLE
Page title is always "title"

### ISSUE THREAD

**Issue by bartekpacia** [dstotijn/go-notion#3]
As the title says. I can't get page titles – they are always equal to `"title"`.

**Comment by bartekpacia** [comment]
Sure, I'm sorry for not doing it – I was in rush😅

### Notion database
It's a simple list of places for an app for tourists
<img width="1145" alt="Screenshot 2021-05-18 at 22 43 35" src="https://user-images.githubusercontent.com/40357511/118721157-ccdb6680-b82a-11eb-8e16-92cb2dc44749.png">

### Code
That's code that I use to retrieve data from that Notion database:
```
func main() {
	flag.Parse()
	client := notion.NewClient(ApiKey)

	filter := notion.DatabaseQuery{Filter: notion.DatabaseQueryFilter{
		Property: "Koordynaty",
		Text:     notion.TextDatabaseQueryFilter{IsNotEmpty: true},
	}}

	res, err := client.QueryDatabase(context.Background(), DatabaseID, filter)
	if err != nil {
		log.Fatalln("exporter: failed to query Notion database:", err)
	}

	page := res.Results[1]
	switch props := page.Properties.(type) {
	case notion.DatabasePageProperties:
		placeRecord := PlaceRecord{
			Title:   props["Nazwa"].ID,
			Type:    props["Typ"].Select.Name,
			Town:    props["Miejscowość"].Select.Name,
			Section: props["Sekcja"].Select.Name,
			Region:  props["Region"].Select.Name,
			Coords:  props["Koordynaty"].RichText[0].PlainText,
		}
		fmt.Printf("%v\n", placeRecord)
	}

	if res.HasMore {
		fmt.Println("exporter: there are more records")
	}
}
```

The output after running that code is:
```
$ go run ./main.go
{title Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19525, 18.44921}
{title Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19488, 18.44946}
{title Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19509, 18.44871}
```

Whereas I'd expect it to be
```
{SomePlaceNameInPolishOne Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19525, 18.44921}
{AnotherPlaceName Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19488, 18.44946}
{SorryForUsingPolishForMyColumns Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19509, 18.44871}
```

The full project is available [here](https://github.com/bartekpacia/discover-rudy-notion-exporter) – I encourage you to clone it and replicate my Notion database with a simple 1 record table. 

It's very possible that I'm simply doing something wrong – I like Go very much, but I use it quite rarely.

**Comment by dstotijn** [comment]
The `ID` of a title property will be always "title" for a DB page. But `props["Nazwa"]` should have other fields that have the actual title value. I'd debug/print it to figure it out. Let me know if this helps, if not I can check out further tomorrow.

**Comment by bartekpacia** [comment]
I'll be grateful if you play around with it.

When I use `Title` to be `props["Nazwa"].RichText[0].PlainText,`, instead of `props["Nazwa"].ID`, it panics.
```
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
main.main()
	/Users/bartek/dev/go/discover-rudy-notion-exporter/main.go:62 +0x8a5
exit status 2
```

**Comment by dstotijn** [comment]
What happens when you try `props["Nazwa"].Title[0].PlainText`?

**Comment by bartekpacia** [comment]
```
$ go run ./main.go
# command-line-arguments
./main.go:62:28: props["Nazwa"].Title undefined (type notion.DatabasePageProperty has no field or method Title)
```

**Comment by dstotijn** [comment]
> ```
> $ go run ./main.go
> # command-line-arguments
> ./main.go:62:28: props["Nazwa"].Title undefined (type notion.DatabasePageProperty has no field or method Title)
> ```
> 
> I don't have `Title` field on my `props` .

Hi Bartek,

There was an issue in `v0.1.0` with parsing titles. If you upgrade to `v0.1.2` it should work:

```sh
$ go run .
{title Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19525, 18.44921}
{title Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19488, 18.44946}
{title Nowe miejsce [Brak info] Rudy Ciekawe miejsce rudy 50.19509, 18.44871}
```

**Note:** You'll have to change the query and filter to pointers (was changed since v0.1.0).

**Comment by bartekpacia** [comment]
Oh yeah, it works now:) thanks a lot and sorry for not being up to date with versions:)
