### ISSUE TITLE
block  no support audio type 

### ISSUE THREAD

**Issue by pkwenda** [dstotijn/go-notion#47]
need get audio info, but fetch is nothing :

![image](https://user-images.githubusercontent.com/14212375/202753379-9d7a03f0-e210-4bc8-9d0c-533248c3506c.png)

**Comment by dstotijn** [comment]
Hi, thanks for raising an issue! Interestingly, the `audio` block type is currently missing from the [official docs](https://developers.notion.com/reference/block) (I've emailed Notion about this). I'll make a PR to add support here in go-notion, based on the [TypeScript defs from the JS SDK](https://github.com/makenotion/notion-sdk-js/blob/main/src/api-endpoints.ts).

**Comment by dstotijn** [comment]
Added in [v0.9.0](https://github.com/dstotijn/go-notion/releases/tag/v0.9.0).

**Comment by pkwenda** [comment]
I'm sorry I just saw the reply, thank you very much for the project and I wish you a happy life :>
